# Generated by Django 3.1.5 on 2021-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField(max_length=200)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('comment', models.TextField()),
                ('comment_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
